- name: CSI Uninstall [monasca]
  hosts: monasca-host
  sudo: yes
  tasks:
    - name: "Disabling services"
      service: name={{ item.name }} state=stopped enabled=no
      with_items: "{{ services }}"

    - name: Removing installed packages [rpm]
      yum: name="{{ item.rpm }}" state=absent
      with_items: "{{ packages[ansible_os_family] }}"
      when: item.rpm is defined

    - name: Removing installed packages [directory]
      file: path={{ item.dir }} state=absent force=yes
      with_items: "{{packages[ansible_os_family]}}"

    - name: Removing installed packages [symlinks]
      file: path={{ item.symlink }} state=absent force=yes
      when: item.symlink is defined
      with_items: "{{packages[ansible_os_family]}}"

      # TODO try to replace two steps below with one
    - name: Delete start/stop scripts [retrieve service file path][SourcePath]
      shell: "systemctl show {{ item.name }} | grep SourcePath | cut -d= -f 2"
      with_items: "{{ services }}"
      register: services_location_sp

    - name: Delete start/stop scripts [retrieve service file path][FragmentPath]
      shell: "systemctl show {{ item.name }} | grep FragmentPath | cut -d= -f 2"
      with_items: "{{ services }}"
      register: services_location_fp

    - name: Delete start/stop scripts [delete service file]
      file: path="{{ item.stdout }}" state=absent force=yes
      with_items:
        - "{{ services_location_sp.results }}"
        - "{{ services_location_fp.results }}"

    - name: Delete configuration files
      file: path={{ item[1] }} state=absent force=yes
      with_subelements:
        - services
        - configuration
