- name: CSI Uninstall [monasca]
  hosts: csi-host
  sudo: yes
  tasks:
    - include: ../tasks/uninstall_services.yml

    - name: Removing installed packages [rpm]
      yum: name="{{ item.rpm }}" state=absent
      with_items: "{{ packages[ansible_os_family] }}"
      when: item.rpm is defined

    - name: Removing installed packages [directory]
      file: path={{ item.dir }} state=absent force=yes
      with_items: "{{packages[ansible_os_family]}}"

    - name: Removing installed packages [symlinks]
      file: path={{ item.symlink }} state=absent force=yes
      when: item.symlink is defined
      with_items: "{{packages[ansible_os_family]}}"
