# This ansible file is only for development usage. It prepares the ansible-master environment to install monasca
---
# Copyright 2016 FUJITSU LIMITED

- name: Prepare Ansible Master Environment
  hosts: all
  sudo: yes
  vars:
    monasca_host: 192.168.10.4
    openstack_host: 192.168.10.5
    ex_node_1_host: 192.168.10.6
    ex_node_2_host: 192.168.10.7
    ex_node_3_host: 192.168.10.8
    balancer_host: 192.168.10.4
    ssh_user_monasca: vagrant
    ssh_user_openstack: vagrant
    ssh_user_ex_node_1: vagrant
    ssh_user_ex_node_2: vagrant
    ssh_user_ex_node_3: vagrant
    ssh_user_balancer: vagrant
    cluster_enabled: "{{ lookup('env', 'ENABLE_CLUSTER') == '1' }}"
  tasks:
    - name: Install epel repository
      yum: name=http://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm state=present
    - name: Import EPEL GPG key
      rpm_key: key="/etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-7" state=present
    - name: Install Ansible
      yum: name=ansible1.9 state=present
    - name: Create custom ansible.cfg file
      template:
        src="templates/ansible.cfg.j2"
        dest="/etc/ansible/ansible.cfg"
        owner=root
        group=root
        mode=0644
    - name: Generate SSH key
      user: name=vagrant generate_ssh_key=yes
    - name: Create ansible-hosts file [single]
      template:
        src="templates/hosts-single.j2"
        dest="/etc/ansible/hosts-single"
        owner=root
        group=root
        mode=0644
      when: not cluster_enabled|bool
    - name: Create ansible-hosts file [cluster]
      template:
        src="templates/hosts-cluster.j2"
        dest="/etc/ansible/hosts-cluster"
        owner=root
        group=root
        mode=0644
      when: cluster_enabled|bool
    - name: Install vim to prevent manual installation step
      yum: name=vim state=present
