# This ansible file is only for development usage. It prepares the ansible-master environment to install monasca
---
# Copyright 2016 FUJITSU LIMITED

- name: Prepare Ansible Master Environment
  hosts: all
  become: true
  vars:
    node_1: 192.168.10.4
    node_1_admin_ip: 192.168.124.4
    node_1_public_ip: 192.168.126.4
    node_1_internal_ip: 192.168.127.4
    node_2: 192.168.10.6
    node_2_admin_ip: 192.168.124.6
    node_2_internal_ip: 192.168.127.6
    node_3: 192.168.10.7
    node_3_admin_ip: 192.168.124.7
    node_3_internal_ip: 192.168.127.7
    node_4: 192.168.10.8
    node_4_admin_ip: 192.168.124.8
    node_4_internal_ip: 192.168.127.8
    ssh_user_node_1: vagrant
    ssh_user_node_2: vagrant
    ssh_user_node_3: vagrant
    ssh_user_node_4: vagrant
    offline_resources_host: 192.168.124.4
    balancer_host: 192.168.10.4
    balancer_host_public_ip: 192.168.126.4
    openstack_host: 192.168.10.5
    openstack_host_admin_ip: 192.168.124.5
    openstack_host_public_ip: 192.168.126.5
    rabbitmq_host: 192.168.10.5
    haproxy_host: 192.168.10.4
    public_network_virtual_ip: 192.168.126.69
    keepalived_virtual_ip: 192.168.10.69
    ssh_user_offline_host: vagrant
    ssh_user_openstack: vagrant
    ssh_user_balancer: vagrant
    cluster_enabled: "{{ lookup('env', 'ENABLE_CLUSTER') == '1' }}"
  tasks:
    - name: Install epel repository
      yum: name=http://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm state=present
    - name: Import EPEL GPG key
      rpm_key: key="/etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-7" state=present
    - name: Install Ansible rpm dependencies
      yum: name="{{ item }}" state="present"
      with_items:
        - gcc
        - openssl
        - openssl-devel
        - python-devel
        - python-pip
        - libffi-devel
    - name: Install Ansible pip dependencies
      pip: name="{{ item }}" state="present"
      with_items:
        - backports.ssl_match_hostname
    - name: Install Ansible
      pip: name=ansible version=2.2.0.0 state=present
    - name: Create custom ansible configuration directory
      file:
        path="/etc/ansible"
        state="directory"
        mode=0755
    - name: Create custom ansible.cfg file
      template:
        src="templates/ansible.cfg.j2"
        dest="/etc/ansible/ansible.cfg"
        mode=0644
    # cluster/single environment operations
    - name: Generate SSH key
      user: name=vagrant generate_ssh_key=yes
    - name: Create ansible-hosts file [single]
      template:
        src="templates/hosts-single.j2"
        dest="/etc/ansible/hosts-single"
        mode=0644
      when: not cluster_enabled|bool
    - name: Create ansible-hosts file [cluster]
      template:
        src="templates/hosts-cluster.j2"
        dest="/etc/ansible/hosts-cluster"
        mode=0644
      when: cluster_enabled|bool
    # extra steps
    - name: Install additional packages to prevent manual installation step
      yum: name="{{ item }}" state=present
      with_items:
        - vim
        - rsync
