---
# Copyright 2016-2017 FUJITSU LIMITED

- name: "Grafana: Prepare/Configure hosts"
  hosts: grafana_group
  become: yes
  vars_files:
    - credentials.yml
  vars:
    credential_keys_list:
      - database_grafana_password
  pre_tasks:
    - include: tasks/verify_ansible.yml
      tags: [always]
    - include: tasks/verify_credentials.yml
      tags: [always]
    - include: tasks/set_up.yml
      tags: [always]
      when: grafana_install_mode == 'rpm'

- name: "Grafana: Install on host"
  hosts: grafana_group
  become: yes
  vars_files:
    - credentials.yml
    - "vars/os_{{ ansible_os_family }}.yml"
  roles:
    - {role: grafana, tags: [grafana]}

- name: "Grafana: Clean-Up host"
  hosts: grafana_group
  become: yes
  post_tasks:
    - include: tasks/clean_up.yml
      tags: [always]
      when: grafana_install_mode == 'rpm'
