---
# Copyright 2016-2017 FUJITSU LIMITED

- name: "Kafka: Prepare/Configure hosts"
  hosts: kafka_group
  become: yes
  pre_tasks:
    - include: tasks/verify_ansible.yml
      tags: [always]
    - include: tasks/set_up.yml
      tags: [always]

- name: "Kafka: Install on hosts"
  hosts: kafka_group
  become: yes
  vars_files:
    - "vars/os_{{ ansible_os_family }}.yml"
  roles:
    - {role: kafka, tags: [kafka]}

- name: "Kafka: Install schema"
  hosts: kafka_group[0]
  become: yes
  vars_files:
    - "vars/os_{{ ansible_os_family }}.yml"
  roles:
    - {role: monasca-schema,
       # kafka nodes should take care only of setting up kafka_schema
       # turn off everything else from monasca-schema
       kafka_topics_enabled: True,
       mysql_schema_enabled: False,
       cassandra_schema_enabled: False,
       winchester_schema_enabled: False,
       vertica_schema_enabled: False,
       postgres_schema_enabled: False,
       influxdb_schema_enabled: False,
       tags: [kafka, schema]}
    - {role: monasca-log-schema,
       tags: [kafka, schema, log_schema]}

- name: "Kafka: Clean-Up hosts"
  hosts: kafka_group
  become: yes
  post_tasks:
    - include: tasks/clean_up.yml
      tags: [always]
