---
# Copyright 2016-2017 FUJITSU LIMITED

- name: "Kibana: Prepare/Configure hosts"
  hosts: kibana_group
  become: yes
  vars_files:
    - credentials.yml
  pre_tasks:
    - include: tasks/verify_ansible.yml
      tags: [always]
    - include: tasks/verify_credentials.yml
      tags: [always]
    - include: tasks/set_up.yml
      tags: [always]

- name: "Kibana: Install on hosts"
  hosts: kibana_group
  become: yes
  vars_files:
    - credentials.yml
    - "vars/os_{{ ansible_os_family }}.yml"
  roles:
    - {
        role: monasca-kibana,
        kibana_configure_network: "{{ configure_network|bool }}",
        tags: [elkstack, kibana]
      }
    - {
        role: logrotate,
        when: ansible_os_family != 'Suse',
        tags: [elkstack, kibana, logrotate]
      }
    - {role: fujitsu-branding, tags: [branding]}

- name: "Kibana: Clean-Up hosts"
  hosts: kibana_group
  become: yes
  post_tasks:
    - include: tasks/clean_up.yml
      tags: [always]
