---
# Copyright 2016-2017 FUJITSU LIMITED

- name: "Memcached: Prepare/ Configure hosts"
  hosts: memcached_group
  become: yes
  vars_files:
    - credentials.yml
  pre_tasks:
    - include: tasks/verify_ansible.yml
      tags: [always]
    - include: tasks/verify_credentials.yml
      tags: [always]
    - include: tasks/set_up.yml
      tags: [always]

- name: "Memcached: Install on host"
  hosts: memcached_group
  become: yes
  vars_files:
    - "vars/os_{{ ansible_os_family }}.yml"
  environment:
    PIP_CONFIG_FILE: "{{ pip_config_file }}"
  roles:
    - {role: memcached, tags: [memcached]}

- name: "Memcached: Clean-Up host"
  hosts: memcached_group
  become: yes
  post_tasks:
    - include: tasks/clean_up.yml
      tags: [always]
