---
- name: Prepare/Configure CSI host
  hosts: csi-node
  sudo: yes
  pre_tasks:
    - include: tasks/set_up.yml tags=pre_tasks
  roles:
    - {role: pip, tags: [pip, resources]}
    - {role: cli-credentials, tags: [cli]}

- name: Monasca Installation
  hosts: csi-node
  sudo: yes
  roles:
    - {role: zookeeper, tags: [zookeeper]}
    - {role: kafka, kafka_listen_address: "{{kafka_host}}", tags: [kafka]}
    - {role: influxdb, tags: [influxdb]}
    - {role: postgresql-redhat,
       when: ansible_os_family == 'RedHat',
       postgresql_repo: "{{ world_repo_url }}/postgresql/",
       postgresql_dir: "/opt/postgresql_91",
       postgresql_data_dir: "{{ postgresql_dir }}/data",
       postgresql_service_name: "postgresql",
       postgresql_tar_filename: "FJSVpgs91_64.tar.gz",
       postgres_install_from_tar: True,
       postgresql_conf_default_guc: [{regexp: "^#?listen_addresses = .*$", guc: "listen_addresses = '127.0.0.1'" }],
       tags: [postgresql]}
    - {role: monasca-schema, database_admin_password: password, tags: [schema]}
    - {role: monasca-log-schema, tags: [elkstack]}
    - {role: monasca-api,
       api_region: useast,
       influxdb_user: mon_api,
       influxdb_password: password,
       database_user: monapi,
       database_password: password,
       monasca_api_tarball_base_url: "{{ world_repo_url }}",
       tags: [api]}
    - {role: monasca-log-api,
       api_region: useast,
       influxdb_user: mon_api,
       influxdb_password: password,
       database_user: monapi,
       database_password: password,
       monasca_log_api_tarball_base_url: "{{ world_repo_url }}",
       tags: [api]}
    - {role: monasca-persister,
       influxdb_user: mon_persister,
       influxdb_password: password,
       tags: [persister]}
    - {role: monasca-notification,
       database_user: notification,
       database_password: password,
       smtp_host: localhost,
       tags: [notification]}
    - {role: storm,
       storm_nimbus_enabled: true,
       storm_supervisor_enabled: true,
       tags: [storm]}
    - {role: monasca-thresh,
       database_user: thresh,
       database_password: password,
       thresh_tarball_base_url: "{{ world_repo_url }}",
       tags: [thresh]}
    - {role: monasca-elkstack,
       elasticsearch_download: "{{ world_repo_url }}",
       logstash_download: "{{ world_repo_url }}",
       kibana_download: "{{ world_repo_url }}",
       tags: [elkstack]}
    - {role: fujitsu-branding, tags: [branding]}

- name: Clean-Up CSI host
  hosts: csi-node
  sudo: yes
  post_tasks:
    - include: tasks/clean_up.yml tags=post_tasks
