---
- name: Prepare/Configure host
  hosts: monasca_agent_group
  sudo: yes
  vars:
    credential_keys_list:
      - cmm_monasca_agent_keystone_password
      - openstack_monasca_agent_keystone_password
      - cmm_monasca_agent_database_password
  vars_files:
    - credentials.yml
  environment:
    PIP_CONFIG_FILE: "{{ pip_config_file }}"
  pre_tasks:
    - include: tasks/verify_ansible.yml
    - include: tasks/verify_pip.yml
    - include: tasks/verify_credentials.yml
      tags: always
    - include: tasks/set_up.yml tags=pre_tasks
  roles:
    - {role: pip, tags: [pip, resources]}

- name: Install Monasca-Agent on host
  hosts: monasca_agent_group
  sudo: yes
  vars_files:
    - credentials.yml
  environment:
    PIP_CONFIG_FILE: "{{ pip_config_file }}"
  roles:
    - {role: monasca-agent, tags: [metric-agent, agents]}

- name: Clean-Up host
  hosts: monasca_agent_group
  sudo: yes
  post_tasks:
    - include: tasks/clean_up.yml tags=post_tasks
