---
# Copyright 2016 FUJITSU LIMITED

- name: "Log Api: Prepare/Configure hosts"
  hosts: monasca_log_api_group
  sudo: yes
  vars:
    credential_keys_list:
      - keystone_admin_password
  vars_files:
    - credentials.yml
  environment:
    PIP_CONFIG_FILE: "{{ pip_config_file }}"
  pre_tasks:
    - include: tasks/verify_credentials.yml
      tags: always
    - include: tasks/set_up.yml tags=log_api
  roles:
    - {role: pip, tags: [pip, resources, log_api]}

- name: "Log Api: Install on hosts"
  hosts: monasca_log_api_group
  sudo: yes
  vars_files:
    - credentials.yml
  environment:
    PIP_CONFIG_FILE: "{{ pip_config_file }}"
  roles:
    - {role: monasca-log-api, tags: [log_api]}

- name: "Log Api: Clean-Up hosts"
  hosts: monasca_log_api_group
  sudo: yes
  post_tasks:
    - include: tasks/clean_up.yml tags=log_api
