---
- name: Install Monasca Log Agent
  hosts: monasca-log-agent
  sudo: yes
  vars:
    offline_mode: True
    # hosts
    offline_host: 192.168.10.4
    openstack_host: 192.168.10.5
    monasca_log_api_host: 192.168.10.4
    keystone_host: "{{ openstack_host }}"
    # offline-resources
    balls_repo_url: "http://{{ offline_host }}:8888"
    logstash_agent_download_url: "{{ world_repo_url }}"
    log_files: ["/var/log/messages","/var/log/yum.log","/var/log/boot.log"]
  roles:
    - {role: pip, skip_install: True, tags: [pip, resources]}
    - {role: monasca-log-agent,
       #project_name: csi,
       #username: csi-agent,
       #password: password,
       #domain_id: default,
       tags: [agent, log-agent]}