---

- name: Uninstall Monasca Metrics Agent
  hosts: monasca_agent_group
  sudo: yes
  tasks:
    - name: Uninstall monasca-agent
      pip: name=monasca-agent state=absent virtualenv="{{ monasca_agent_venv_dir }}"
      ignore_errors: True

- name: Uninstall Monasca Metrics Agent
  hosts: monasca_agent_group
  sudo: yes
  roles:
    - {role: uninstaller,
      uninstall_skip_pip: True,
      tags: [uninstaller, uninstaller_monasca_agent ]}
