---
- name: Install Monasca Metrics Agent
  hosts: monasca-metrics-agent
  sudo: yes
  vars:
    offline_mode: True
    # hosts
    offline_host: 192.168.10.4
    openstack_host: 192.168.10.5
    # urls
    balls_repo_url: "http://{{ offline_host }}:8888"
    world_repo_url: "{{ balls_repo_url }}/world"
    get_pip_download_url: "{{ world_repo_url }}"
    pip_index_url: "{{ balls_repo_url }}/local-pip-cache/simple"
    pip_extra_index_url: "{{ balls_repo_url }}/pip-cache/simple"
    # monasca-agent
    keystone_url: "http://{{ openstack_host }}:35357/v3"
    monasca_agent:
      user: monasca-agent
      password: password
      project: mini-mon
  roles:
    - {role: pip, skip_install: True, tags: [pip, resources]}
    - {role: monasca-agent, tags: [agent, metric-agent]}
