---
# Copyright 2016 FUJITSU LIMITED

- name: Prepare/Configure host
  hosts: monasca_agent_group
  become: yes
  vars:
    credential_keys_list:
      - keystone_cmm_agent_password
      - keystone_admin_agent_password
  vars_files:
    - credentials.yml
  environment:
    PIP_CONFIG_FILE: "{{ pip_config_file }}"
  pre_tasks:
    - include: tasks/verify_ansible.yml
      tags: [always]
    - include: tasks/verify_pip.yml
      tags: [always]
    - include: tasks/verify_credentials.yml
      tags: [always]
    - include: tasks/set_up.yml
      tags: [always]
  roles:
    - {role: pip, tags: [pip, resources]}

- name: Install Monasca-Agent on host
  hosts: monasca_agent_group
  become: yes
  vars_files:
    - credentials.yml
  environment:
    PIP_CONFIG_FILE: "{{ pip_config_file }}"
  roles:
    - {role: monasca-agent, tags: [metric-agent, agents]}

- name: Clean-Up host
  hosts: monasca_agent_group
  become: yes
  post_tasks:
    - include: tasks/clean_up.yml
      tags: [always]
