---
# Copyright 2016 FUJITSU LIMITED

- name: Prepare/Configure host
  hosts: monasca_log_agent_group
  become: yes
  vars:
    credential_keys_list:
      - cmm_monasca_log_agent_keystone_password
      - openstack_monasca_log_agent_keystone_password
  vars_files:
    - credentials.yml
  pre_tasks:
    - include: tasks/verify_ansible.yml
      tags: [always]
    - include: tasks/verify_credentials.yml
      tags: [always]
    - include: tasks/set_up.yml
      tags: [pre_tasks]

- name: Install Monasca-Log-Agent
  hosts: monasca_log_agent_group
  become: yes
  vars_files:
    - credentials.yml
  roles:
    - {role: logrotate, tags: [logrotate]}
    - {role: monasca-log-agent, tags: [log-agent, agents]}

- name: Clean-Up host
  hosts: monasca_log_agent_group
  become: yes
  post_tasks:
    - include: tasks/clean_up.yml
      tags: [post_tasks]
