---
# Copyright 2016-2017 FUJITSU LIMITED

- name: Prepare/Configure host
  hosts: monasca_log_agent_group
  become: yes
  vars:
    credential_keys_list:
      - keystone_cmm_agent_password
      - keystone_admin_agent_password
  vars_files:
    - credentials.yml
  pre_tasks:
    - include: tasks/verify_ansible.yml
      tags: [always]
    - include: tasks/verify_credentials.yml
      tags: [always]
    - include: tasks/set_up.yml
      tags: [always]

- name: Install Monasca-Log-Agent
  hosts: monasca_log_agent_group
  become: yes
  vars_files:
    - credentials.yml
    - "vars/os_{{ ansible_os_family }}.yml"
  roles:
    - {role: monasca-log-agent, tags: [log-agent, agents]}
    - {role: logrotate, when: ansible_os_family != 'Suse', tags: [logrotate]}

- name: Clean-Up host
  hosts: monasca_log_agent_group
  become: yes
  post_tasks:
    - include: tasks/clean_up.yml
      tags: [always]
