---
- name: Prepare/Configure host
  hosts: monasca_agent_group
  sudo: yes
  vars_files:
    - credentials.yml
  pre_tasks:
    - include: tasks/set_up.yml tags=pre_tasks
    - include: tasks/verify_credentials.yml tags=agents,metric-agent
  roles:
    - {role: pip, tags: [pip, resources]}

- name: Install Monasca-Agent on host
  hosts: monasca_agent_group
  sudo: yes
  vars_files:
    - credentials.yml
  roles:
    - {role: monasca-agent, tags: [metric-agent, agents]}

- name: Clean-Up host
  hosts: monasca_agent_group
  sudo: yes
  post_tasks:
    - include: tasks/clean_up.yml tags=post_tasks
