---
# Copyright 2016 FUJITSU LIMITED

- name: "Monasca Group: Verify credentials"
  hosts: monasca_group
  become: yes
  vars:
    credential_keys_list:
      - influxdb_mon_api_password
      - influxdb_mon_persister_password
      - database_notification_password
      - database_monapi_password
      - database_thresh_password
      - keystone_monasca_operator_password
      - keystone_admin_password
  vars_files:
    - credentials.yml
  pre_tasks:
    - include: tasks/verify_ansible.yml
      tags: [always]
    - include: tasks/verify_credentials.yml
      tags: [always]

- include: memcached.yml
- include: zookeeper.yml
- include: kafka.yml
- include: elasticsearch.yml
- include: elasticsearch-curator.yml
- include: kibana.yml
- include: monasca-log-api.yml
- include: monasca-log-transformer.yml
- include: monasca-log-persister.yml
- include: monasca-log-metrics.yml
- include: storm.yml
- include: mariadb.yml
- include: influxdb.yml
- include: keepalived.yml
- include: haproxy.yml
- include: monasca-thresh.yml
- include: monasca-notification.yml
- include: monasca-persister.yml
- include: monasca-api.yml
- include: grafana.yml
