---
# Copyright 2016-2017 FUJITSU LIMITED

- name: "monasca-persister: Prepare/Configure hosts"
  hosts: monasca_persister_group
  become: yes
  vars:
    credential_keys_list:
      - influxdb_mon_persister_password
  vars_files:
    - credentials.yml
  pre_tasks:
    - include: tasks/verify_ansible.yml
      tags: [always]
    - include: tasks/verify_credentials.yml
      tags: [always]
    - include: tasks/set_up.yml
      tags: [always]

- name: "monasca-persister: Install on hosts"
  hosts: monasca_persister_group
  become: yes
  vars_files:
    - credentials.yml
    - "vars/os_{{ ansible_os_family }}.yml"
  roles:
    - {role: monasca-persister, tags: [persister]}

- name: "monasca-persister: Clean-Up hosts"
  hosts: monasca_persister_group
  become: yes
  post_tasks:
    - include: tasks/clean_up.yml
      tags: [always]

# TODO(trebskit) if monasca-persister would be used in python implementation
# this playbook should install pip as well
