---
# Copyright 2016-2017 FUJITSU LIMITED

- name: "Log Persister: Prepare/Configure hosts"
  hosts: monasca_log_persister_group
  become: yes
  vars_files:
    - credentials.yml
  pre_tasks:
    - include: tasks/verify_ansible.yml
      tags: [always]
    - include: tasks/verify_credentials.yml
      tags: [always]
    - include: tasks/set_up.yml
      tags: [always]

- name: "Log Persister: Install on hosts"
  hosts: monasca_log_persister_group
  become: yes
  vars_files:
    - "vars/os_{{ ansible_os_family }}.yml"
  roles:
    - {role: monasca-log-persister, tags: [elkstack, log_persister]}
    - {
        role: logrotate,
        when: ansible_os_family != 'Suse',
        tags: [elkstack, logrotate, log_persister]
      }

- name: "Log Persister: Clean-Up hosts"
  hosts: monasca_log_persister_group
  become: yes
  post_tasks:
    - include: tasks/clean_up.yml
      tags: [always]
