---
- name: Uninstall Monasca Log Agent
  hosts: monasca_log_agent_group
  sudo: yes
  roles:
    - {role: uninstaller,
      uninstall_skip_pip: True,
      tags: [uninstaller, uninstaller_monasca_log_agent]}
