---
# Copyright 2016-2017 FUJITSU LIMITED

- name: "monasca-notification: Prepare/Configure hosts"
  hosts: monasca_notification_group
  become: yes
  vars:
    credential_keys_list:
      - database_notification_password
  vars_files:
    - credentials.yml
    - "vars/os_{{ ansible_os_family }}.yml"
  pre_tasks:
    - include: tasks/verify_ansible.yml
      tags: [always]
    - include: tasks/verify_pip.yml
      tags: [always]
    - include: tasks/verify_credentials.yml
      tags: [always]
    - include: tasks/set_up.yml
      tags: [always]
  roles:
    - {role: pip, tags: [pip, resources, notification]}

- name: "monasca-notification: Install on hosts"
  hosts: monasca_notification_group
  become: yes
  vars_files:
    - credentials.yml
    - "vars/os_{{ ansible_os_family }}.yml"
  environment:
    PIP_CONFIG_FILE: "{{ pip_config_file }}"
  roles:
    - {role: monasca-notification, tags: [notification]}

- name: "monasca-notification: Clean-Up hosts"
  hosts: monasca_notification_group
  become: yes
  post_tasks:
    - include: tasks/clean_up.yml
      tags: [always]
