---
# Copyright 2016 FUJITSU LIMITED

- name: Uninstall Monasca Log Agent
  hosts: monasca_log_agent_group
  become: yes
  pre_tasks:
    - include: tasks/verify_ansible.yml
      tags: [always]
  roles:
    - {role: uninstaller,
      uninstall_skip_pip: True,
      tags: [uninstaller, uninstaller_monasca_log_agent]}
