---
# Copyright 2016 FUJITSU LIMITED

- name: Prepare/Configure host
  hosts: cmm-node
  sudo: yes
  vars:
    credential_keys_list:
      - database_notification_password
      - database_thresh_password
  vars_files:
    - credentials.yml
  environment:
    PIP_CONFIG_FILE: "{{ pip_config_file }}"
  pre_tasks:
    - include: tasks/verify_ansible.yml
    - include: tasks/verify_pip.yml
    - include: tasks/verify_credentials.yml
      tags: [always]
    - include: tasks/set_up.yml
      tags: [pre_tasks]
  roles:
    - {role: pip, tags: [pip, resources]}
    - {role: cli-credentials, tags: [cli]}

- name: Monasca Installation
  hosts: cmm-node
  vars_files:
    - credentials.yml
  sudo: yes
  environment:
    PIP_CONFIG_FILE: "{{ pip_config_file }}"
  roles:
    - {role: influxdb, tags: [influxdb]}
    - {role: mariadb, tags: [mariadb]}
    - {role: monasca-schema,
       kafka_topics_enabled: False,
       tags: [schema]}
    - {role: logrotate, tags: [logrotate]}

- name: Clean-Up host
  hosts: cmm-node
  sudo: yes
  post_tasks:
    - include: tasks/clean_up.yml
      tags: [post_tasks]
