---
# Copyright 2016 FUJITSU LIMITED

- name: Prepare/Configure host
  hosts: cmm-node
  sudo: yes
  vars:
    credential_keys_list:
      - database_notification_password
      - database_thresh_password
  vars_files:
    - credentials.yml
  environment:
    PIP_CONFIG_FILE: "{{ pip_config_file }}"
  pre_tasks:
    - include: tasks/verify_credentials.yml
      tags: always
    - include: tasks/set_up.yml tags=pre_tasks
  roles:
    - {role: pip, tags: [pip, resources]}
    - {role: cli-credentials, tags: [cli]}

- name: Monasca Installation
  hosts: cmm-node
  vars_files:
    - credentials.yml
  sudo: yes
  environment:
    PIP_CONFIG_FILE: "{{ pip_config_file }}"
  roles:
    - {role: influxdb, tags: [influxdb]}
    - {role: mariadb, tags: [mariadb]}
    - {role: monasca-schema,
       kafka_topics_enabled: False,
       tags: [schema]}
    - {role: storm,
       storm_nimbus_enabled: true,
       storm_supervisor_enabled: true,
       tags: [storm]}
    - {role: monasca-thresh,
       database_user: thresh,
       database_password: "{{ database_thresh_password }}",
       thresh_tarball_base_url: "{{ world_repo_url }}",
       tags: [thresh]}
    - {role: logrotate, tags: [logrotate]}

- name: Clean-Up host
  hosts: cmm-node
  sudo: yes
  post_tasks:
    - include: tasks/clean_up.yml tags=post_tasks
