---
- name: Prepare/Configure CSI host
  hosts: monasca-host
  sudo: yes
  pre_tasks:
    - include: tasks/set_up.yml tags=pre_tasks
  roles:
    - {role: pip, tags: [pip, resources]}
    - {role: cli-credentials, is_openstack: true, tags: [cli]}

- name: Monasca Installation
  hosts: monasca-host
  sudo: yes
  roles:
    - {role: zookeeper, tags: [zookeeper]}
    - {role: kafka, kafka_listen_address: "{{ monasca_host }}", tags: [kafka]}
    - {role: influxdb, tags: [influxdb]}
    - {role: postgresql-redhat,
       when: ansible_os_family == 'RedHat',
       postgresql_repo: "/opt/monasca/storage/balls/postgresql",
       postgresql_dir: "/opt/postgresql_91",
       postgresql_data_dir: "{{ postgresql_dir }}/data",
       postgresql_service_name: "postgres_fuji",
       postgresql_tar_filename: "/opt/monasca/storage/balls/world/postgresql/FJSVpgs91_64.tar.gz",
       postgres_install_from_tar: True,
       tags: [postgresql]}
    - {role: monasca-schema, database_admin_password: password, tags: [schema]}
    - {role: monasca-log-schema, tags: [elkstack]}
    - {role: monasca-api,
       api_region: useast,
       influxdb_user: mon_api,
       influxdb_password: password,
       database_user: monapi,
       database_password: password,
       monasca_api_tarball_base_url: "{{ world_repo_url }}",
       tags: [api]}
    - {role: monasca-log-api,
       api_region: useast,
       influxdb_user: mon_api,
       influxdb_password: password,
       database_user: monapi,
       database_password: password,
       monasca_log_api_tarball_base_url: "{{ world_repo_url }}",
       tags: [api]}
    - {role: monasca-persister,
       influxdb_user: mon_persister,
       influxdb_password: password,
       tags: [persister]}
    - {role: monasca-notification,
       database_user: notification,
       database_password: password,
       smtp_host: localhost,
       tags: [notification]}
    - {role: storm,
       nimbus_host: "{{ monasca_host }}",
       storm_nimbus_enabled: true,
       storm_supervisor_enabled: true,
       tags: [storm]}
    - {role: monasca-thresh,
       database_user: thresh,
       database_password: password,
       thresh_tarball_base_url: "{{ world_repo_url }}",
       tags: [thresh]}
    - {role: monasca-elkstack,
       elasticsearch_download: "{{ world_repo_url }}",
       logstash_download: "{{ world_repo_url }}",
       kibana_download: "{{ world_repo_url }}",
       tags: [elkstack]}

- name: Install Monasca-Agent on CSI
  hosts: monasca-monasca-agent
  sudo: yes
  roles:
    - {role: monasca-agent, tags: [metric-agent, agents]}

- name: Install Monasca-Log-Agent on CSI
  hosts: monasca-monasca-log-agent
  sudo: yes
  roles:
    - {role: monasca-log-agent, tags: [log-agent, agents]}

- name: Clean-Up CSI host
  hosts: monasca-host
  sudo: yes
  post_tasks:
    - include: tasks/clean_up.yml tags=post_tasks
