---
# Copyright 2016-2017 FUJITSU LIMITED
# Copyright 2018 SUSE Linux GmbH

- name: "Monasca-api: Prepare/ Configure hosts"
  hosts: monasca_api_group
  become: yes
  vars:
    credential_keys_list:
      - cassandra_mon_api_password
      - influxdb_mon_api_password
      - database_monapi_password
  vars_files:
    - credentials.yml
  pre_tasks:
    - include: tasks/verify_ansible.yml
      tags: [always]
    - include: tasks/verify_credentials.yml
      tags: [always]
    - include: tasks/set_up.yml
      tags: [always]

- name: "Monasca-api: Install on hosts"
  hosts: monasca_api_group
  vars_files:
    - credentials.yml
    - "vars/os_{{ ansible_os_family }}.yml"
  become: yes
  roles:
    - {
        role: monasca-api,
        monasca_api_configure_network: "{{ configure_network|bool }}",
        tags: [api]
      }

- name: "Monasca-api: Clean-Up hosts"
  hosts: monasca_api_group
  become: yes
  post_tasks:
    - include: tasks/clean_up.yml
      tags: [always]
