---
# Copyright 2016 FUJITSU LIMITED

- name: Install Offline resources
  hosts: offline-resources-node
  become: yes
  environment:
    PIP_CONFIG_FILE: "{{ pip_config_file }}"
  pre_tasks:
    - include: tasks/verify_ansible.yml
      tags: [always]
    - include: tasks/verify_pip.yml
      tags: [always]
    - include: tasks/set_up.yml
      tags: [always]
  roles:
    - {role: monasca-resources, tags: [storage, resources]}
    - {role: static-http, tags: [static-http, resources], pip_trusted_host: "{{ offline_host }}" }
    - {role: pip, tags: [pip, resources]}
