---
- name: Install Offline resources
  hosts: offline-resources-host
  sudo: yes
  pre_tasks:
    - include: tasks/set_up.yml
  roles:
    - {role: monasca-resources, tags: [storage, resources]}
    - {role: static-http, tags: [static-http, resources], pip_trusted_host: "{{ offline_host }}" }
    - {role: pip, tags: [pip, resources]}
