---
- name: Install Offline resources
  hosts: offline
  sudo: yes
  vars:
    # hosts
    offline_host: 127.0.0.1
    # url
    balls_repo_url: "http://{{ offline_host }}:8888"
    world_repo_url: "{{ balls_repo_url }}/world"
    get_pip_download_url: "{{ world_repo_url }}"
  roles:
    - {role: monasca-resources, tags: [storage, resources]}
    - {role: static-http, tags: [static-http, resources],
       pip_index_url: "{{balls_repo_url}}/local-pip-cache/simple",
       pip_extra_index_url: "{{balls_repo_url}}/pip-cache/simple"}