---
# Copyright 2016 FUJITSU LIMITED

- name: Prepare/Configure Horizon host
  hosts: horizon-node
  sudo: yes
  vars:
    credential_keys_list:
      - keystone_cmm_operator_user_password
      - keystone_cmm_agent_password
      - keystone_admin_password
      - keystone_admin_agent_password
  vars_files:
    - credentials.yml
  pre_tasks:
    - include: tasks/verify_ansible.yml
    - include: tasks/verify_pip.yml
    - include: tasks/verify_credentials.yml
      tags: always
    - include: tasks/set_up.yml tags=pre_tasks
  environment:
    PIP_CONFIG_FILE: "{{ pip_config_file }}"
  roles:
    - {role: pip, tags: [pip, resources]}
    - {role: cli-credentials, tags: [cli]}

- name: Prepare/Configure Keystone host
  hosts: keystone-node
  sudo: yes
  vars_files:
    - credentials.yml
  environment:
    PIP_CONFIG_FILE: "{{ pip_config_file }}"
  pre_tasks:
    - include: tasks/verify_pip.yml
    - include: tasks/set_up.yml tags=pre_tasks
  roles:
    - {role: pip, tags: [pip, resources]}
    - {role: cli-credentials, tags: [cli]}

- name: Install Horizon components
  hosts: horizon-node
  sudo: yes
  environment:
    PIP_CONFIG_FILE: "{{ pip_config_file }}"
  roles:
    - {role: monasca-ui,
       grafana_tarball_url: "{{ balls_repo_url }}/world",
       grafana_tarball_file: "/fujitsu-monasca-grafana.tar.gz",
       monasca_ui_name: "monasca-ui",
       tags: [ui]}
    - {role: fujitsu-branding, tags: [branding]}
    - {role: horizon-patch, tags: [horizon-patch]}

- name: Configure Keystone
  hosts: keystone-node
  sudo: yes
  environment:
    PIP_CONFIG_FILE: "{{ pip_config_file }}"
  vars:
    credential_keys_list:
      - keystone_cmm_operator_user_password
      - keystone_cmm_agent_password
      - keystone_admin_password
      - keystone_admin_agent_password
  pre_tasks:
    - include: tasks/verify_credentials.yml
      tags: always
  vars_files:
    - credentials.yml
  roles:
    - {role: monasca-keystone, tags: [keystone]}

- name: Clean-Up Openstack hosts
  hosts: horizon-node
  sudo: yes
  post_tasks:
    - include: tasks/clean_up.yml tags=post_tasks

- name: Clean-Up Openstack hosts
  hosts: keystone-node
  sudo: yes
  post_tasks:
    - include: tasks/clean_up.yml tags=post_tasks
