---
- name: Install Monasca Devstack components
  hosts: openstack
  sudo: yes
  vars:
    # hosts
    offline_host: 192.168.10.4
    devstack_host: 192.168.10.5
    monasca_host: 192.168.10.4
    # urls
    monasca_api_url: "http://{{ monasca_host }}:8080/v2.0"
    keystone_url: "http://{{ devstack_host }}:35357/v3"
    kibana_url: "http://{{ monasca_host }}:5601/"
    # offline mode information
    offline_mode: True
    balls_repo_url: "http://{{ offline_host }}:8888"
    world_repo_url: "{{ balls_repo_url }}/world"
    epel_download_url: "{{ world_repo_url }}"
    install_epel: False
    remove_network_manager: False
    # keystone
    keystone_admin_token: ADMIN
    keystone_users:
      - username: mini-mon
        project: mini-mon
        password: password
        role: monasca-user
      - username: monasca-agent
        password: password
        project: mini-mon
        role: monasca-agent
    # monasca agent
    monasca_agent:
      user: monasca-agent
      password: password
      project: mini-mon
    kibana_host: "http://{{ monasca_host }}:5601/"
  tasks:
    - name: Setup the monasca cli credentials in the default environment
      copy: src=tests/env.sh dest=/etc/profile.d/monasca_cli.sh owner=root group=root mode=0644
      tags:
        - cli
    - name: Update cli
      pip: name=python-monascaclient state=latest
      tags:
        - cli
  roles:
    - {role: monasca-devstack, tags: [devstack]}
    - {role: monasca-ui,
       grafana_tarball_url: "{{ world_repo_url }}",
       grafana_tarball_file: "/hpcloud-mon-grafana-v1.5.4-903-gbbe7c09.tar.gz",
       monasca_ui_name: "monasca-ui",
       tags: [ui]}
    - {role: monasca-keystone, tags: [devstack, keystone]}
    #- {role: monasca-agent, tags: [agent]}
