---
- name: Prepare/Configure Horizon host
  hosts: horizon-host
  sudo: yes
  pre_tasks:
    - include: tasks/set_up.yml tags=pre_tasks
  roles:
    - {role: pip, tags: [pip, resources]}
    - {role: cli-credentials, tags: [cli]}

- name: Prepare/Configure Keystone host
  hosts: keystone-host
  sudo: yes
  pre_tasks:
    - include: tasks/set_up.yml tags=pre_tasks
  roles:
    - {role: pip, tags: [pip, resources]}
    - {role: cli-credentials, tags: [cli]}

- name: Install Horizon components
  hosts: horizon-host
  sudo: yes
  roles:
    - {role: monasca-ui,
       grafana_tarball_url: "{{ balls_repo_url }}/world",
       grafana_tarball_file: "/fujitsu-mon-grafana-fbdf1a7.tar.gz",
       monasca_ui_name: "monasca-ui",
       tags: [ui]}
    - {role: fujitsu-branding, tags: [branding]}

- name: Configure Keystone
  hosts: keystone-host
  sudo: yes
  roles:
    - {role: monasca-keystone, tags: [keystone]}

- name: Clean-Up Openstack hosts
  hosts: horizon-host
  sudo: yes
  post_tasks:
    - include: tasks/clean_up.yml tags=post_tasks

- name: Clean-Up Openstack hosts
  hosts: keystone-host
  sudo: yes
  post_tasks:
    - include: tasks/clean_up.yml tags=post_tasks