---
- name: Prepare/Configure Openstack host
  hosts: openstack-host
  sudo: yes
  pre_tasks:
    - include: tasks/set_up.yml tags=pre_tasks
  roles:
    - {role: pip, tags: [pip, resources]}
    - {role: cli-credentials, tags: [cli]}

- name: Install Monasca Openstack components
  hosts: openstack-host
  sudo: yes
  roles:
    - {role: monasca-devstack, tags: [devstack]}
    - {role: monasca-ui,
       grafana_tarball_url: "{{ balls_repo_url }}/world",
       grafana_tarball_file: "/fujitsu-mon-grafana-fbdf1a7.tar.gz",
       monasca_ui_name: "monasca-ui",
       tags: [ui]}
    - {role: monasca-keystone, tags: [devstack, keystone]}
    - {role: fujitsu-branding, tags: [branding]}

- name: Install Monasca-Agent on openstack
  hosts: openstack-monasca-agent
  sudo: yes
  roles:
    - {role: monasca-agent, tags: [metric-agent, agents]}

- name: Install Monasca-Log-Agent on openstack
  hosts: openstack-monasca-log-agent
  sudo: yes
  roles:
    - {role: monasca-log-agent, tags: [log-agent, agents]}

- name: Clean-Up Openstack host
  hosts: openstack-host
  sudo: yes
  post_tasks:
    - include: tasks/clean_up.yml tags=post_tasks
