---
- name: Install Monasca Devstack components
  hosts: openstack
  sudo: yes
  vars:
    # hosts
    offline_host: 192.168.10.4
    monasca_host: 192.168.10.4
    keystone_host: 192.168.10.5
    # urls
    monasca_api_url: "http://{{ monasca_host }}:8080/v2.0"
    keystone_url: "http://{{ keystone_host }}:35357/v3"
    kibana_url: "http://{{ monasca_host }}:5601/"
    logstash_agent_download_url: "{{ world_repo_url }}"
    # offline mode information
    offline_mode: True
    balls_repo_url: "http://{{ offline_host }}:8888"
    world_repo_url: "{{ balls_repo_url }}/world"
    epel_download_url: "{{ world_repo_url }}"
    install_epel: False
    remove_network_manager: False
    # keystone
    keystone_admin_token: ADMIN
    keystone_admin: 'admin'
    keystone_admin_password: 'admin'
    keystone_admin_project: 'admin'
    keystone_users:
      - username: csi-operator
        project: csi
        password: password
        role: csi-user
      - username: csi-operator
        project: csi
        password: password
        role: admin
      - username: csi-agent
        project: csi
        password: password
        role: csi-agent
      - username: admin
        project: admin
        password: admin
        role: csi-user
      - username: admin-agent
        project: admin
        password: admin
        role: csi-agent
    # monasca agent
    monasca_agent:
      user: admin-agent
      password: admin
      project: admin
    monasca_checks:
      host_alive:
        init_config:
          ssh_port: 22
          ssh_timeout: 0.5
          ping_timeout: 1
        instances:
          - name: monasca
            host_name: "{{ monasca_host }}"
            alive_test: ssh
    kibana_host: "http://{{ monasca_host }}:5601/"
    monasca_log_api_host: "192.168.10.4"
    # urls
  tasks:
    - name: Setup the monasca cli credentials in the default environment
      copy: src=tests/env.sh dest=/etc/profile.d/monasca_cli.sh owner=root group=root mode=0644
      tags:
        - cli
    - name: Update cli
      pip: name=python-monascaclient state=present extra_args='--pre'
      tags:
        - cli
  roles:
    - {role: monasca-devstack, tags: [devstack]}
    - {role: monasca-ui,
       grafana_tarball_url: "{{ world_repo_url }}",
       grafana_tarball_file: "/hpcloud-mon-grafana-v1.5.4-903-gbbe7c09.tar.gz",
       monasca_ui_name: "monasca-ui",
       tags: [ui]}
    - {role: monasca-keystone, tags: [devstack, keystone]}
    - {role: monasca-agent, tags: [metric-agent, agents]}
    - {role: monasca-log-agent,
       project_name: admin,
       username: admin-agent,
       password: admin,
       domain_id: default,
       tags: [log-agent, agents]}