---
- name: Prepare/Configure Horizon host
  hosts: horizon-node
  sudo: yes
  pre_tasks:
    - include: tasks/set_up.yml tags=pre_tasks
    - include: tasks/verify_credentials.yml tags=verify_passwords,pre_tasks,cli
  vars_files:
    - credentials.yml
  roles:
    - {role: pip, tags: [pip, resources]}
    - {role: cli-credentials, tags: [cli]}

- name: Prepare/Configure Keystone host
  hosts: keystone-node
  sudo: yes
  vars_files:
    - credentials.yml
  pre_tasks:
    - include: tasks/set_up.yml tags=pre_tasks
    - include: tasks/verify_credentials.yml tags=verify_passwords,pre_tasks,cli
  roles:
    - {role: pip, tags: [pip, resources]}
    - {role: cli-credentials, tags: [cli]}

- name: Install Horizon components
  hosts: horizon-node
  sudo: yes
  roles:
    - {role: monasca-ui,
       grafana_tarball_url: "{{ balls_repo_url }}/world",
       grafana_tarball_file: "/fujitsu-mon-grafana-20a75b0.tar.gz",
       monasca_ui_name: "monasca-ui",
       tags: [ui]}
    - {role: fujitsu-branding, tags: [branding]}

- name: Configure Keystone
  hosts: keystone-node
  sudo: yes
  pre_tasks:
    - include: tasks/verify_credentials.yml tags=verify_passwords,pre_tasks,keystone
  vars_files:
    - credentials.yml
  roles:
    - {role: monasca-keystone, tags: [keystone]}

- name: Clean-Up Openstack hosts
  hosts: horizon-node
  sudo: yes
  post_tasks:
    - include: tasks/clean_up.yml tags=post_tasks

- name: Clean-Up Openstack hosts
  hosts: keystone-node
  sudo: yes
  post_tasks:
    - include: tasks/clean_up.yml tags=post_tasks
