---
# Copyright 2016-2017 FUJITSU LIMITED

- name: Prepare/Configure Horizon host
  hosts: horizon-node
  become: yes
  vars:
    credential_keys_list:
      - keystone_monasca_operator_password
      - keystone_monasca_agent_password
      - keystone_admin_password
      - keystone_admin_agent_password
  vars_files:
    - credentials.yml
    - "vars/os_{{ ansible_os_family }}.yml"
  pre_tasks:
    - include: tasks/verify_ansible.yml
      tags: [always]
    - include: tasks/verify_pip.yml
      tags: [always]
    - include: tasks/verify_credentials.yml
      tags: [always]
    - include: tasks/set_up.yml
      tags: [always]
  environment:
    PIP_CONFIG_FILE: "{{ pip_config_file }}"
  roles:
    - {role: pip, tags: [pip, resources]}

- name: Prepare/Configure Keystone host
  hosts: keystone-node
  become: yes
  vars_files:
    - credentials.yml
    - "vars/os_{{ ansible_os_family }}.yml"
  pre_tasks:
    - include: tasks/verify_pip.yml
      tags: [always]
    - include: tasks/set_up.yml
      tags: [always]
  environment:
    PIP_CONFIG_FILE: "{{ pip_config_file }}"
  roles:
    - {role: pip, tags: [pip, resources]}

- name: Install Horizon components
  hosts: horizon-node
  become: yes
  vars_files:
    - "vars/os_{{ ansible_os_family }}.yml"
  environment:
    PIP_CONFIG_FILE: "{{ pip_config_file }}"
  roles:
    - {role: monasca-ui,
       monasca_ui_name: "monasca-ui",
       tags: [ui]}
    - {role: fujitsu-branding, tags: [branding]}
    - {role: horizon-patch, tags: [horizon-patch]}

- name: Configure Keystone
  hosts: keystone-node
  become: yes
  vars_files:
    - credentials.yml
    - "vars/os_{{ ansible_os_family }}.yml"
  vars:
    credential_keys_list:
      - keystone_monasca_operator_password
      - keystone_monasca_agent_password
      - keystone_admin_password
      - keystone_admin_agent_password
  pre_tasks:
    - include: tasks/verify_credentials.yml
      tags: [always]
  environment:
    PIP_CONFIG_FILE: "{{ pip_config_file }}"
  roles:
    - {role: monasca-keystone, tags: [keystone]}

- name: Clean-Up Openstack hosts
  hosts: horizon-node
  become: yes
  post_tasks:
    - include: tasks/clean_up.yml
      tags: [always]

- name: Clean-Up Openstack hosts
  hosts: keystone-node
  become: yes
  post_tasks:
    - include: tasks/clean_up.yml
      tags: [always]
