- src: https://gitlab.com/monasca-installer/ansible-cli-credentials.git
  scm: git
  version: master
  name: cli-credentials
- src: https://gitlab.com/monasca-installer/ansible-elasticsearch-curator.git
  scm: git
  version: master
  name: elasticsearch-curator
- src: https://gitlab.com/monasca-installer/ansible-influxdb.git
  scm: git
  version: master
  name: influxdb
- src: https://gitlab.com/monasca-installer/ansible-galera.git
  scm: git
  version: master
  name: galera
- src: https://gitlab.com/monasca-installer/ansible-grafana.git
  scm: git
  version: master
  name: grafana
- src: https://gitlab.com/monasca-installer/ansible-haproxy.git
  scm: git
  version: master
  name: haproxy
- src: https://gitlab.com/monasca-installer/ansible-horizon-patch.git
  scm: git
  version: master
  name: horizon-patch
- src: https://gitlab.com/monasca-installer/ansible-kafka.git
  scm: git
  version: master
  name: kafka
- src: https://gitlab.com/monasca-installer/ansible-keepalived.git
  scm: git
  version: master
  name: keepalived
- src: https://gitlab.com/monasca-installer/ansible-load-balancer.git
  scm: git
  version: master
  name: load-balancer
- src: https://gitlab.com/monasca-installer/ansible-logrotate.git
  scm: git
  version: master
  name: logrotate
- src: https://gitlab.com/monasca-installer/ansible-mariadb.git
  scm: git
  version: master
  name: mariadb
- src: https://gitlab.com/monasca-installer/ansible-memcached.git
  scm: git
  version: master
  name: memcached
- src: https://gitlab.com/monasca-installer/ansible-monasca-agent.git
  scm: git
  version: master
  name: monasca-agent
- src: https://gitlab.com/monasca-installer/ansible-monasca-api.git
  scm: git
  version: master
  name: monasca-api
- src: https://gitlab.com/monasca-installer/ansible-monasca-elasticsearch.git
  scm: git
  version: master
  name: monasca-elasticsearch
- src: https://gitlab.com/monasca-installer/ansible-monasca-keystone.git
  scm: git
  version: master
  name: monasca-keystone
- src: https://gitlab.com/monasca-installer/ansible-monasca-kibana.git
  scm: git
  version: master
  name: monasca-kibana
- src: https://gitlab.com/monasca-installer/ansible-monasca-log-agent.git
  scm: git
  version: master
  name: monasca-log-agent
- src: https://gitlab.com/monasca-installer/ansible-monasca-log-api.git
  scm: git
  version: master
  name: monasca-log-api
- src: https://gitlab.com/monasca-installer/ansible-monasca-log-metrics.git
  scm: git
  version: master
  name: monasca-log-metrics
- src: https://gitlab.com/monasca-installer/ansible-monasca-log-persister.git
  scm: git
  version: master
  name: monasca-log-persister
- src: https://gitlab.com/monasca-installer/ansible-monasca-log-schema.git
  scm: git
  version: master
  name: monasca-log-schema
- src: https://gitlab.com/monasca-installer/ansible-monasca-log-transformer.git
  scm: git
  version: master
  name: monasca-log-transformer
- src: https://gitlab.com/monasca-installer/ansible-monasca-notification.git
  scm: git
  version: master
  name: monasca-notification
- src: https://gitlab.com/monasca-installer/ansible-monasca-persister.git
  scm: git
  version: master
  name: monasca-persister
- src: https://gitlab.com/monasca-installer/ansible-monasca-schema.git
  scm: git
  version: master
  name: monasca-schema
- src: https://gitlab.com/monasca-installer/ansible-monasca-thresh.git
  scm: git
  version: master
  name: monasca-thresh
- src: https://gitlab.com/monasca-installer/ansible-monasca-ui.git
  scm: git
  version: master
  name: monasca-ui
- src: https://gitlab.com/monasca-installer/ansible-pip.git
  scm: git
  version: master
  name: pip
- src: https://gitlab.com/monasca-installer/ansible-storm.git
  scm: git
  version: master
  name: storm
- src: https://gitlab.com/monasca-installer/ansible-uninstaller.git
  scm: git
  version: master
  name: uninstaller
- src: https://gitlab.com/monasca-installer/ansible-zookeeper.git
  scm: git
  version: master
  name: zookeeper
