---
# Copyright 2016 FUJITSU LIMITED

- name: "Storm: Prepare/ Configure hosts"
  hosts: storm_group
  become: yes
  vars_files:
    - credentials.yml
  pre_tasks:
    - include: tasks/verify_ansible.yml
      tags: [always]
    - include: tasks/set_up.yml
      tags: [always]

- name: "Storm: Install Nimbus on host"
  hosts: storm_nimbus_group
  become: yes
  pre_tasks:
    - include: tasks/verify_ansible.yml
      tags: [always]
  roles:
    - {role: storm, tags: [storm, storm-nimbus] }

- name: "Storm: Install Supervisor on host"
  hosts: storm_supervisor_group
  become: yes
  pre_tasks:
    - include: tasks/verify_ansible.yml
      tags: [always]
  roles:
    - {role: storm, tags: [storm, storm-supervisor] }

- name: "Storm: Clean-Up host"
  hosts: storm_group
  become: yes
  post_tasks:
    - include: tasks/clean_up.yml
      tags: [always]
