---
# Copyright 2016 FUJITSU LIMITED

- name: "Storm: Prepare/ Configure hosts"
  hosts: storm_group
  sudo: yes
  vars_files:
    - credentials.yml
  pre_tasks:
    - include: tasks/verify_ansible.yml
      tags: [always]
    - include: tasks/set_up.yml
      tags: [always]

- name: "Storm: Install on host"
  hosts: storm_group
  sudo: yes
  pre_tasks:
    - include: tasks/verify_ansible.yml
  roles:
    - {role: storm, tags: [storm] }

- name: "Storm: Clean-Up host"
  hosts: storm_group
  sudo: yes
  post_tasks:
    - include: tasks/clean_up.yml
      tags: [always]
