---
# Copyright 2016 FUJITSU LIMITED

- name: Uninstall [monasca]
  hosts: cmm-node
  sudo: yes
  pre_tasks:
    - include: tasks/verify_ansible.yml
  roles:
    - {role: uninstaller, tags: [uninstaller, uninstaller_monasca]}

- name: Uninstall [openstack][horizon-node]
  hosts: horizon-node
  sudo: yes
  roles:
    - {role: uninstaller, tags: [uninstaller, uninstaller_openstack, uninstaller_horizon]}

- name: Uninstall [openstack][keystone-node]
  hosts: keystone-node
  sudo: yes
  roles:
    - {role: uninstaller, tags: [uninstaller, uninstaller_openstack, uninstaller_keystone]}
