---
# Copyright 2016-2017 FUJITSU LIMITED

# Experimental approach to remove components
- name: "Uninstall Grafana"
  hosts: grafana_group
  become: yes
  vars_files:
    - "vars/os_{{ ansible_os_family }}.yml"
  pre_tasks:
    - include: tasks/verify_ansible.yml
      tags: [always]
  roles:
    - {role: grafana,
       run_mode: 'purge',
       tags: [uninstaller, uninstaller_grafana]}

- name: Uninstall [monasca]
  hosts: monasca_uninstaller
  become: yes
  vars_files:
    - "vars/os_{{ ansible_os_family }}.yml"
  pre_tasks:
    - include: tasks/verify_ansible.yml
      tags: [always]
  roles:
    - {role: uninstaller, tags: [uninstaller, uninstaller_monasca]}

- name: Uninstall [openstack][horizon-node]
  hosts: openstack_uninstaller_group
  become: yes
  vars_files:
    - "vars/os_{{ ansible_os_family }}.yml"
  pre_tasks:
    - include: tasks/verify_ansible.yml
      tags: [always]
  roles:
    - {role: uninstaller, tags: [uninstaller, uninstaller_openstack, uninstaller_horizon]}

- name: Uninstall [openstack][keystone-node]
  hosts: keystone-node
  become: yes
  vars_files:
    - "vars/os_{{ ansible_os_family }}.yml"
  pre_tasks:
    - include: tasks/verify_ansible.yml
      tags: [always]
  roles:
    - {role: uninstaller, tags: [uninstaller, uninstaller_openstack, uninstaller_keystone]}
