---
# Copyright 2016 FUJITSU LIMITED

- name: Verify that passwords were set.
  hosts: localhost
  become: yes
  vars:
    credential_keys_list:
      - influxdb_mon_api_password
      - influxdb_mon_persister_password
      - database_notification_password
      - database_monapi_password
      - database_thresh_password
      - keystone_monasca_operator_password
      - keystone_monasca_agent_password
      - keystone_admin_agent_password
      - keystone_admin_password
  vars_files:
    - credentials.yml
  pre_tasks:
    - include: tasks/verify_ansible.yml
      tags: [always]
    - include: tasks/verify_credentials.yml
      tags: [always]
