---
- name: Verify that passwords were set.
  hosts: localhost
  sudo: yes
  vars:
    credential_keys_list:
      - influxdb_mon_api_password
      - influxdb_mon_persister_password
      - database_notification_password
      - database_monapi_password
      - database_thresh_password
      - database_logapi_password
      - cmm_monasca_agent_keystone_password
      - cmm_monasca_log_agent_keystone_password
      - cmm_monasca_agent_database_password
      - keystone_cmm_operator_user_password
      - keystone_cmm_agent_password
      - keystone_admin_agent_password
      - keystone_admin_password
      - openstack_monasca_agent_keystone_password
      - openstack_monasca_log_agent_keystone_password
  vars_files:
    - credentials.yml
  pre_tasks:
    - include: tasks/verify_ansible.yml
    - include: tasks/verify_credentials.yml
