---
# Copyright 2016 FUJITSU LIMITED

- name: Prepare/Configure hosts
  hosts: zookeeper_group
  become: yes
  vars_files:
    - credentials.yml
  pre_tasks:
    - include: tasks/verify_ansible.yml
      tags: [always]
    - include: tasks/verify_credentials.yml
      tags: [always]
    - include: tasks/set_up.yml
      tags: [always]

- name: Install on hosts
  hosts: zookeeper_group
  become: yes
  roles:
    - {role: zookeeper, tags: [zookeeper]}

- name: Clean-Up hosts
  hosts: zookeeper_group
  become: yes
  post_tasks:
   - include: tasks/clean_up.yml
     tags: [always]
