- fail: msg="Password {{ item }} has not been set. Please set up passwords in credentials.yml file"
  with_items: "{{ credential_keys_list }}"
  when: "{{ item }} is undefined or {{ item }} is none or {{ item|trim }} == ''"
