---
# Copyright 2016-2017 FUJITSU LIMITED

- name: Include system specific variables
  include_vars: "os_{{ ansible_os_family }}.yml"

- name: Check if passwords were set
  fail: msg="Password {{ item }} has not been set. Please set up passwords in credentials.yml file"
  with_items: "{{ credential_keys_list | default([]) }}"
  when: "{{ item }} is undefined or {{ item }} is none or {{ item|trim }} == ''"
