---
- name: Gather OS Specific Variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
    - "defaults.yml"

- include: apt-packages.yml
  when: ansible_pkg_mgr == 'apt'
- include: yum_packages.yml
  when: ansible_pkg_mgr == 'yum'

- name: create/update mysql config
  template: dest={{ mysql_cnf_file }} owner=root group=root mode=0600 src=my_cnf.j2
  notify:
    - run monasca-setup
